import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.rest.api.domain.SafelySurrenderedBabies
import gov.ca.cwds.data.legacy.cms.entity.SafelySurrenderedBabies
global java.util.Set validationDetailsList
rule "R-07993"
  dialect "mvel"
  agenda-group "safely-surrender-babies-agenda"
  when  
      $safelyBaby: SafelySurrenderedBabies()
      $safelySurrenderedBabies: SafelySurrenderedBabies(surrenderedByName != null) from  $safelyBaby.entity
  then
      IssueDetails details = new IssueDetails(); 
      details.setCode("R-07993");
      details.setUserMessage("failed");
      details.setTechnicalMessage("failed");
      System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$**R-07993 is activated*********************************************************************************** ");
      validationDetailsList.add(details);
end   