import gov.ca.cwds.rest.exception.IssueDetails
import gov.ca.cwds.data.legacy.cms.entity.SafelySurrenderedBabies
import org.apache.commons.lang3.StringUtils;

global java.util.Set validationDetailsList
rule "R-07993"
  dialect "mvel"
  agenda-group "safely-surrender-babies-agenda"
  when  
      $safelyBaby: SafelySurrenderedBabies(medicalQuestionnaireCode == "R", surrenderedDate != null, questionnaireReceivedDate == null)
  then
	  $safelyBaby.setQuestionnaireReceivedDate($safelyBaby.getSurrenderedDate());
	  modify ($safelyBaby);
end   