import gov.ca.cwds.rest.api.domain.cms.Address
import gov.ca.cwds.security.realm.PerryAccount

global java.util.Set validationDetailsList

rule "R-07993"
  dialect "mvel"
  agenda-group "referrals-address-data-processing-agenda"
  when
      $address: Address(state == (short)1838, city != null)
      $perryAccount: PerryAccount()
  then
      $address.setGovernmentEntityCd(Short.parseShort($perryAccount.getCountyCwsCode()));
      modify($address);   
end