applicationName: CWDS API

swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS API
  description: RESTful API definitions for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png
  
dataSourceFactory:
  driverClass: com.ibm.db2.jcc.DB2Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: ${DB_JDBC_URL}
  validationQuery: "/* MyService Health Check */ SELECT 1 FROM sysibm.sysdummy1"
  logValidationErrors: true
  initialSize: 2
  minSize: 2
  maxSize: 8
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.show_sql: true
      hibernate.default_schema: ${DB_SCHEMA}
      

flywayFactory:
  sqlMigrationPrefix: v
  schemas:
    - CWSINT
  locations:
    - db/migrations
    
server:
  applicationConnectors:
  - type: http 
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
