applicationName: CWDS API
version: ${APP_VERSION:-local}

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro.ini}"]

swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS API
  description: RESTful API definitions for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png
  showSwagger: ${SHOW_SWAGGER:-true}
  jsonUrl: ${SWAGGER_JSON_URL:-http://localhost:8080/swagger.json}
  loginUrl: ${LOGIN_URL:-http://localhost:8090/authn/login}
  logoutUrl: ${LOGOUT_URL:-http://localhost:8080/perry/authn/logout}
  callbackUrl: ${SWAGGER_CALLBACK_URL:-http://localhost:8080/swagger}
  tokenUrl: ${SWAGGER_TOKEN_URL:-http://localhost:8080/perry/authn/token}

upgradeDbOnStart: ${UPGRADE_DB_ON_START:-false}

nsDataSourceFactory:
  driverClass: org.postgresql.Driver
  user: ${DB_NS_USER}
  password: ${DB_NS_PASSWORD}
  url: ${DB_NS_JDBC_URL}
  validationQuery: "/* MyService Health Check */ SELECT 1 FOR READ ONLY"
  logValidationErrors: true
  initialSize: ${DB_NS_CP_INITIAL_SIZE:-2}
  minSize: ${DB_NS_CP_MIN_SIZE:-2}
  maxSize: ${DB_NS_CP_MAX_SIZE:-20}
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: gov.ca.cwds.data.persistence.hibernate.dialect.JsonPostgreSQLDialect
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.id.new_generator_mappings: false
      hibernate.show_sql: ${FERB_HIBERNATE_SHOW_SQL:-false}
      hibernate.format_sql: ${FERB_HIBERNATE_FORMAT_SQL:-true}
      hibernate.default_schema: ${DB_NS_SCHEMA:-intakens}
      hibernate.connection.autocommit: false
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.isolation: 2
      # connection.logAbandoned: true

cmsDataSourceFactory:
  autoCommitByDefault: false
  driverClass: com.ibm.db2.jcc.DB2Driver
  user: ${DB_CMS_USER}
  password: ${DB_CMS_PASSWORD}
  url: ${DB_CMS_JDBC_URL}
  validationQuery: "/* CMS DB2 Health Check */ SELECT 1 FROM SYSIBM.SYSDUMMY1 FOR READ ONLY WITH UR"
  logValidationErrors: true
  initialSize: ${DB_CMS_CP_INITIAL_SIZE:-2}
  minSize: ${DB_CMS_CP_MIN_SIZE:-2}
  maxSize: ${DB_CMS_CP_MAX_SIZE:-20}
  minIdleTime: 1 minute
  maxConnectionAge: ${DB_CMS_MAX_AGE:-30s}
  removeAbandoned: ${DB_CMS_REMOVE_ABANDONED:-false}
  removeAbandonedTimeout: ${DB_CMS_REMOVE_ABANDONED_TIMEOUT:-1200s}
  commitOnReturn: ${DB_CMS_COMMIT_ON_RETURN:-false}
  checkConnectionWhileIdle: ${DB_CMS_CHECK_CONNECTION_WHILE_IDLE:-true}
  checkConnectionOnBorrow: ${DB_CMS_CHECK_CONNECTION_ON_BORROW:-false}
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.show_sql: ${FERB_HIBERNATE_SHOW_SQL:-false}
      hibernate.format_sql: ${FERB_HIBERNATE_FORMAT_SQL:-true}
      hibernate.use_sql_comments: true
      hibernate.default_schema: ${DB_CMS_SCHEMA}
      hibernate.connection.autocommit: false
      hibernate.connection.isolation: 2
      # connection.debugUnreturnedConnectionStackTraces: true
      # connection.logAbandoned: true
      # hibernate.connection.provider_disables_autocommit: true
      # hibernate.current_session_context_class: thread

rsDataSourceFactory:
  autoCommitByDefault: false
  driverClass: com.ibm.db2.jcc.DB2Driver
  user: ${DB_CWSRS_USER}
  password: ${DB_CWSRS_PASSWORD}
  url: ${DB_CWSRS_JDBC_URL}
  validationQuery: "/* RS DB2 Health Check */ SELECT 1 FROM SYSIBM.SYSDUMMY1 FOR READ ONLY WITH UR"
  logValidationErrors: true
  initialSize: ${DB_CWSRS_CP_INITIAL_SIZE:-2}
  minSize: ${DB_CWSRS_CP_MIN_SIZE:-2}
  maxSize: ${DB_CWSRS_CP_MAX_SIZE:-20}
  minIdleTime: 1 minute
  maxConnectionAge: ${DB_CWSRS_MAX_AGE:-30s}
  removeAbandoned: ${DB_CWSRS_REMOVE_ABANDONED:-false}
  removeAbandonedTimeout: ${DB_CWSRS_REMOVE_ABANDONED_TIMEOUT:-1200s}
  commitOnReturn: ${DB_CWSRS_COMMIT_ON_RETURN:-false}
  checkConnectionWhileIdle: ${DB_CWSRS_CHECK_CONNECTION_WHILE_IDLE:-true}
  checkConnectionOnBorrow: ${DB_CWSRS_CHECK_CONNECTION_ON_BORROW:-false}
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.show_sql: ${FERB_HIBERNATE_SHOW_SQL:-false}
      hibernate.format_sql: ${FERB_HIBERNATE_FORMAT_SQL:-true}
      hibernate.use_sql_comments: true
      hibernate.default_schema: ${DB_CWSRS_SCHEMA}
      hibernate.connection.autocommit: false
      hibernate.connection.isolation: 2

##==========================
## XA DATA SOURCES:
##==========================

xaCmsDataSourceFactory:
  autoCommitByDefault: false
  driverClass: com.ibm.db2.jcc.DB2Driver
  user: ${DB_CMS_USER}
  password: ${DB_CMS_PASSWORD}
  url: ${DB_CMS_JDBC_URL}
  xaDataSourceClassName: com.ibm.db2.jcc.DB2XADataSource
  validationQuery: "/* XA/CMS Health Check */ SELECT 1 FROM SYSIBM.SYSDUMMY1 FOR READ ONLY WITH UR"
  logValidationErrors: true
  initialSize: ${DB_CMSXA_CP_INITIAL_SIZE:-2}
  minSize: ${DB_CMSXA_CP_MIN_SIZE:-2}
  maxSize: ${DB_CMSXA_CP_MAX_SIZE:-20}
  minIdleTime: 1 minute
  maxConnectionAge: ${DB_CMSXA_MAX_AGE:-30s}
  removeAbandoned: ${DB_CMS_REMOVE_ABANDONED:-false}
  removeAbandonedTimeout: ${DB_CMSXA_REMOVE_ABANDONED_TIMEOUT:-1200s}
  commitOnReturn: ${DB_CMSXA_COMMIT_ON_RETURN:-false}
  checkConnectionWhileIdle: ${DB_CMSXA_CHECK_CONNECTION_WHILE_IDLE:-true}
  checkConnectionOnBorrow: ${DB_CMSXA_CHECK_CONNECTION_ON_BORROW:-false}
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.show_sql: ${FERB_HIBERNATE_SHOW_SQL:-false}
      hibernate.format_sql: ${FERB_HIBERNATE_FORMAT_SQL:-true}
      hibernate.default_schema: ${DB_CMS_SCHEMA}
      hibernate.connection.autocommit: false
      hibernate.current_session_context_class: jta
      hibernate.transaction.jta.platform: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
      hibernate.transaction.factory_class: gov.ca.cwds.data.persistence.xa.CaresJtaTransactionCoordinatorBuilderImpl
      hibernate.connection.release_mode: after_transaction
      hibernate.connection.isolation: 2
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: false
      connection.release_mode: after_transaction
      connection.timerLevelForQueryTimeOut: 2
      connection.blockingReadConnectionTimeout: 90
      hibernate.cache.provider_class: org.hibernate.cache.NoCacheProvider
      # hibernate.connection.provider_disables_autocommit: true
      # hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  xaProperties:
      # Properties for DB2XADataSource
      serverName: ${DB_CMS_HOST:-localhost}
      portNumber: ${DB_CMS_PORT:-50000}
      databaseName: ${DB_CMS_SERVICE:-DB0TDEV}
      driverType: 4 # Type4 connection for DB2 DataSource
      minPoolSize=: ${DB_CMSXA_CP_INITIAL_SIZE:-2}
      maxPoolSize: ${DB_CMSXA_CP_MAX_SIZE:-20}
      reapTimeout: ${DB_CMSXA_REAP_TIMEOUT:-300}
      maxIdleTime: ${DB_CMSXA_MAX_IDLE:-30}
      maxLifetime: ${DB_CMSXA_LIFETIME:-60}
      maintenanceInterval: ${DB_CMSXA__MAINT_INTERVAL:-60}
      borrowConnectionTimeout: ${DB_CMSXA_BORROW_TIME:-30}

xaCmsRsDataSourceFactory:
  autoCommitByDefault: false
  driverClass: com.ibm.db2.jcc.DB2Driver
  user: ${DB_CWSRS_USER}
  password: ${DB_CWSRS_PASSWORD}
  url: ${DB_CWSRS_JDBC_URL}
  xaDataSourceClassName: com.ibm.db2.jcc.DB2XADataSource
  validationQuery: "/* XA/CMS Health Check */ SELECT 1 FROM SYSIBM.SYSDUMMY1 FOR READ ONLY WITH UR"
  logValidationErrors: true
  initialSize: ${DB_CWSRSXA_CP_INITIAL_SIZE:-2}
  minSize: ${DB_CWSRSXA_CP_MIN_SIZE:-2}
  maxSize: ${DB_CWSRSXA_CP_MAX_SIZE:-20}
  minIdleTime: 1 minute
  maxConnectionAge: ${DB_CWSRSXA_MAX_AGE:-30s}
  removeAbandoned: ${DB_CWSRSXA_REMOVE_ABANDONED:-false}
  removeAbandonedTimeout: ${DB_CWSRSXA_REMOVE_ABANDONED_TIMEOUT:-1200s}
  commitOnReturn: ${DB_CWSRSXA_COMMIT_ON_RETURN:-false}
  checkConnectionWhileIdle: ${DB_CWSRSXA_CHECK_CONNECTION_WHILE_IDLE:-true}
  checkConnectionOnBorrow: ${DB_CWSRSXA_CHECK_CONNECTION_ON_BORROW:-false}
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.show_sql: ${FERB_HIBERNATE_SHOW_SQL:-false}
      hibernate.format_sql: ${FERB_HIBERNATE_FORMAT_SQL:-true}
      hibernate.default_schema: ${DB_CWSRS_SCHEMA}
      hibernate.connection.autocommit: false
      hibernate.current_session_context_class: jta
      hibernate.transaction.jta.platform: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
      hibernate.transaction.factory_class: gov.ca.cwds.data.persistence.xa.CaresJtaTransactionCoordinatorBuilderImpl
      hibernate.connection.release_mode: after_transaction
      connection.release_mode: after_transaction
      hibernate.connection.isolation: 2
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: false
      connection.timerLevelForQueryTimeOut: 2
      connection.blockingReadConnectionTimeout: 90
      hibernate.cache.provider_class: org.hibernate.cache.NoCacheProvider
      # hibernate.connection.provider_disables_autocommit: true
      # hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  xaProperties:
      # Properties for DB2XADataSource
      serverName: ${DB_CMS_HOST:-localhost}
      portNumber: ${DB_CMS_PORT:-50000}
      databaseName: ${DB_CMS_SERVICE:-DB0TDEV}
      driverType: 4 # Type4 connection for DB2 DataSource
      minPoolSize=: ${DB_CMSXA_CP_INITIAL_SIZE:-2}
      maxPoolSize: ${DB_CMSXA_CP_MAX_SIZE:-20}
      reapTimeout: ${DB_CMSXA_REAP_TIMEOUT:-300}
      maxIdleTime: ${DB_CMSXA_MAX_IDLE:-30}
      maxLifetime: ${DB_CMSXA_LIFETIME:-60}
      maintenanceInterval: ${DB_CMSXA__MAINT_INTERVAL:-60}
      borrowConnectionTimeout: ${DB_CMSXA_BORROW_TIME:-30}

xaNsDataSourceFactory:
  driverClass: org.postgresql.Driver
  user: ${DB_NS_USER}
  password: ${DB_NS_PASSWORD}
  url: ${DB_NS_JDBC_URL}
  xaDataSourceClassName: org.postgresql.xa.PGXADataSource
  validationQuery: "/* XA/NS Health Check */ SELECT 1 FOR READ ONLY"
  logValidationErrors: true
  initialSize: 2
  minSize: 2
  maxSize: ${XA_DB_NS_CP_MAX_SIZE:-20}
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: gov.ca.cwds.data.persistence.hibernate.dialect.JsonPostgreSQLDialect
      hibernate.id.new_generator_mappings: false
      hibernate.show_sql: ${FERB_HIBERNATE_SHOW_SQL:-false}
      hibernate.format_sql: ${FERB_HIBERNATE_FORMAT_SQL:-true}
      hibernate.default_schema: ${DB_NS_SCHEMA:-intakens}
      hibernate.connection.autocommit: false
      hibernate.current_session_context_class: jta
      hibernate.transaction.jta.platform: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
      hibernate.transaction.factory_class: gov.ca.cwds.data.persistence.xa.CaresJtaTransactionCoordinatorBuilderImpl
      hibernate.connection.release_mode: after_transaction
      connection.release_mode: after_transaction
      hibernate.connection.isolation: 2
      hibernate.temp.use_jdbc_metadata_defaults: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_second_level_cache: false
      connection.timerLevelForQueryTimeOut: 2
      connection.blockingReadConnectionTimeout: 90
      # hibernate.connection.provider_disables_autocommit: true
      # hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  xaProperties:
      url: ${DB_NS_JDBC_URL}
      minPoolSize=: ${DB_CMSXA_CP_INITIAL_SIZE:-2}
      maxPoolSize: ${DB_CMSXA_CP_MAX_SIZE:-20}
      reapTimeout: ${DB_CMSXA_REAP_TIMEOUT:-300}
      maxIdleTime: ${DB_CMSXA_MAX_IDLE:-30}
      maxLifetime: ${DB_CMSXA_LIFETIME:-60}
      maintenanceInterval: ${DB_CMSXA__MAINT_INTERVAL:-60}
      borrowConnectionTimeout: ${DB_CMSXA_BORROW_TIME:-30}

testConfig:
  path: ${TEST_FILE_PATH:-config/testConfig.yml}

triggertables:
  laCountySpecificCode: 19

systemCodeCache:
  preLoad: ${PRE_LOAD_SYSTEM_CODE_CACHE:-true}
  refreshAfter: ${SYSTEM_CODE_CACHE_REFRESH_AFTER:-31536000}

webSecurity:
  httpResponseSecurityHeaders:
    # Prevent MIMI sniffing
    X-Content-Type-Options: nosniff

    # Prevent click-jacking
    X-Frame-Options: deny

    # Prevent cross site scripting
    X-XSS-Protection: 1; mode=block

    # Prevent everything other than same origin
    Content-Security-Policy: default-src 'self' 'unsafe-inline';

sundial:
  thread-pool-size: 10
  shutdown-on-unload: true
  wait-on-shutdown: false
  start-delay-seconds: 0
  start-scheduler-on-load: true
  global-lock-on-load: false
  tasks: [startjob, stopjob, addcronjobtrigger]

server:
  applicationConnectors:
  - type: http
    port: ${APP_STD_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${APP_ADMIN_PORT:-8081}

  requestLog:
    appenders:
      - type: console
    # - type: file

logging:
  level: ${LOGLEVEL:-DEBUG}
  loggers:
    "org.hibernate.SQL":
      # Use DEBUG to see SQL logged
      level: ${LOGLEVEL_HIBERNATE_SQL:-DEBUG}
    "org.hibernate.type.descriptor.sql":
      # Use TRACE to see SQL parameters logged
      level: ${LOGLEVEL_HIBERNATE_PARAMS:-DEBUG}
    "gov.ca.cwds.data.ApiHibernateInterceptor":
      # Use DEBUG or TRACE to see entities logged
      level: ${LOGLEVEL_HIBERNATE_INTERCEPTOR:-DEBUG}
    "com.atomikos.jdbc":
      level: ${LOGLEVEL_XA_TRANSACTION:-DEBUG}
    "org.eclipse.jetty":
      level: ${LOGLEVEL_JETTY:-DEBUG}
    "io.dropwizard.server":
      level: INFO
    "io.dropwizard.jersey.DropwizardResourceConfig":
      level: INFO
    "AUDIT":
      level: ${LOGLEVEL:-DEBUG}
  appenders:
    - type: console
      threshold: DEBUG
      timeZone: UTC
      target: stdout
      logFormat: '[%date{ISO8601}] [LEVEL=%level] [REMOTE_ADDRESS=%X{REMOTE_ADDRESS}] [REQUEST_ID=%X{REQUEST_ID}] [SESSION_ID=%X{SESSION_ID}] [STAFF_ID=%X{STAFF_ID}] [STAFF_COUNTY=%X{STAFF_COUNTY}] [RESPONSE_STATUS=%X{RESPONSE_STATUS}] [THREAD=%thread] [LOGGER=%logger] [MESSAGE=%message] [THROWABLE=%throwable]%n'

#   - type: file
#     currentLogFilename: logs/ferb.log
#     threshold: ALL
#     queueSize: 512
#     discardingThreshold: 0
#     maxFileSize: 20MB
#     archive: true
#     archivedLogFilenamePattern: logs/ferb-%i.log
#     archivedFileCount: 5
#     timeZone: UTC
#     logFormat: '[%date{ISO8601}] [LEVEL=%level] [REMOTE_ADDRESS=%X{REMOTE_ADDRESS}] [REQUEST_ID=%X{REQUEST_ID}] [SESSION_ID=%X{SESSION_ID}] [STAFF_ID=%X{STAFF_ID}] [STAFF_COUNTY=%X{STAFF_COUNTY}] [RESPONSE_STATUS=%X{RESPONSE_STATUS}] [THREAD=%thread] [LOGGER=%logger] [MESSAGE=%message] [THROWABLE=%throwable]%n'
